version: '2'
services:
  mymvc:
    build:
      context: ./mymvc
      dockerfile: Dockerfile
    expose:
      - "5000"
  proxy2:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links :
      - mymvc



     